// <auto-generated />
namespace Sw_Trazabilidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agregada_relacion_materiaprima_proveedor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregada_relacion_materiaprima_proveedor));
        
        string IMigrationMetadata.Id
        {
            get { return "201805110506058_Agregada_relacion_materiaprima_proveedor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
