// <auto-generated />
namespace Sw_Trazabilidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cambiado_nombre_tablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambiado_nombre_tablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050324506_Cambiado_nombre_tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
