// <auto-generated />
namespace Sw_Trazabilidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cuit_de_int_a_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cuit_de_int_a_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050359008_Cuit_de_int_a_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
