// <auto-generated />
namespace Sw_Trazabilidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Otros_cambios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Otros_cambios));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050523454_Otros_cambios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
